name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas tqdm regex pdfplumber pytz wget pygsheets
      - name: Run the scraping script
        run: python EGLE-AQD-violation-parser-mapbuilder.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      - name: Run the google sheets updater script
        env:
          sheets_service_auth: ${{ secrets.PYG_SHEETS_AUTH }}
        run: python sheets-updater.py
